---
- name: Import repo file 
  hosts: nodes_all
  gather_facts: yes
  vars:
      repo_centos7:
        - {src: '../files/CentOS7-Base.repo'}
        - {src: '../files/epel7.repo'}
      repo_rocky8:
        - {src: '../files/Rocky8-all.repo'}
        - {src: '../files/epel8.repo'}

  tasks:
    - name: Include common vars
      include_vars: file=../vars/vars.yml

    - name: Back up the repo file 
      shell: mv /etc/yum.repos.d/*.repo /etc/yum.repos.d/bak

    - name: Copy repo-7 file 
      copy:
        src: "{{ item.src }}"
        dest: '/etc/yum.repos.d/'
        mode: "{{directory_permission}}"
        # owner: "{{deploy_user}}"
        # group: "{{vincent_group}}"
      with_items: "{{repo_centos7}}"
      when: ansible_distribution_major_version == "7"
      tags: centos7_yum_repos

    - name: Copy repo-8 file 
      copy:
        src: "{{ item.src }}"
        dest: '/etc/yum.repos.d/'
        mode: "{{directory_permission}}"
        # owner: "{{deploy_user}}"
        # group: "{{vincent_group}}"
      with_items: "{{repo_rocky8}}"
      when: ansible_distribution_major_version == "8"
      tags: rocky8_yum_repos