---
- name: linux kernel update
  hosts: nodes_all
  gather_facts: yes
  tasks:
    - name: Include common vars
      include_vars: file=../vars/vars.yml

    - name: linux kernel update ( quite slow ) #更新所有包
      yum: name='*' state=latest update_cache=yes

#     - name: update
#       shell: yum update -y
#     # - name: centos7 kernel update 
#     #   yum: name='*' state=latest update_cache=yes
#     #   when: ansible_distribution_major_version == "7"
#     #   tags: centos7_kernel_update 

    # - name: rocky8 kernel update 
    #   yum: name='*' state=latest update_cache=yes
      # when: ansible_distribution_major_version == "8"
      # tags: rocky8_kernel_update 
