---
- name: Create user&group
  hosts: nodes_all
  gather_facts: no
  tasks:
    - name: Include common vars
      include_vars: file=../vars/vars.yml

    - name: add group
      group:
        name: "{{ item.name }}"
        gid: "{{ item.gid }}"
        state: present
      loop: "{{ grouplist }}"
      tags: user

    - name: add user 
      user: 
        name: "{{ item.name }}" 
        password: "{{ item.pass | password_hash('sha512') }}"
        uid: "{{ item.uid }}"
        groups: "{{ item.groups }}"
        state: present
      loop: "{{ userlist }}"
      tags: user

    # - name: Set up multiple authorized keys
    #   authorized_key:
    #     user: '{{ sudo_key_user }}'
    #     state: present
    #     key: '{{ item }}'
    #   with_file:
    #     - ansible_key/id_rsa.pub
    #     - blueking_key/id_rsa.pub
    #   tags: user

    - name: Config /etc/sudoers
      lineinfile: dest=/etc/sudoers state=present  line='{{item}}' 
      with_items:
        - "{{ deploy_user }} ALL=(ALL) NOPASSWD: ALL"
      tags: user
